FROM ruby:2.7.0

RUN apt-get update && apt-get install -y nodejs npm && npm install --global yarn

WORKDIR /app

COPY ./vote-no-destino-app/Gemfile ./vote-no-destino-app/Gemfile.lock ./

RUN bundle install

COPY ./vote-no-destino-app .

RUN rails webpacker:install
RUN rails assets:precompile

EXPOSE 3000

CMD ["rails", "server", "-b", "0.0.0.0"]