version: '3'
networks:
  vnd-network:
    driver: bridge
services:
  vote_no_destino_db:
    image: mysql:5.7
    container_name: vote_no_destino_db
    environment:
      MYSQL_DATABASE: vote_no_destino_development
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_PASSWORD: mypass
    networks:
      - vnd-network
    ports:
      - "3307:3306"

  web:
    build:
      dockerfile: Dockerfile.development
      context: .
    container_name: web
    volumes:
      - "./vote-no-destino-app:/app"
    environment:
      TZ: America/Sao_Paulo
      RAILS_ENV: development
      DB_HOST: vote_no_destino_db
      DB_USER: user
      DB_USER_PASSWORD: mypass
    command: bash -c "rm -f tmp/pids/server.pid && rails s -p 3000 -b '0.0.0.0'"
    networks:
      - vnd-network
    ports:
      - "8080:3000"
    depends_on:
      - vote_no_destino_db
    links:
      - vote_no_destino_db

  web-production:
    build: .
    container_name: web-production
    volumes:
      - "./vote-no-destino-app:/app"
    environment:
      TZ: America/Sao_Paulo
      RAILS_ENV: production
      DB_DATABASE_HEROKU: heroku_5b84b079c4052b9
      DB_HOST: us-cdbr-east-02.cleardb.com
      DB_USER: b0f54f8a881c92
      DB_USER_PASSWORD: 7573afc6
      RAILS_SERVE_STATIC_FILES: 1
    command: bash -c "rm -f tmp/pids/server.pid && rails s -p 3000 -b '0.0.0.0'"
    networks:
      - vnd-network
    ports:
      - "8080:3000"
